project:
  type: website

website:
  title: "Black Lab Analytics"
  site-url: "https://blacklabanalytics.ai"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



